#!/bin/sh

set -e

cd /opt/asahi-fedora

echo ""
echo "Downloading install script"
wget -q https://asahi-fedora-remix.org/install -O ./install

echo ""
echo "Configuring script"
echo ""
eval $(grep -E 'export\W+(VERSION_FLAG|INSTALLER_BASE|INSTALLER_DATA|REPO_BASE)=' ./install | tee /dev/stderr)

echo ""
echo "Fetching packages"

PACKAGES=$(curl -sL ${INSTALLER_DATA} | jq -r ' .os_list[]
    | select((.package | split("-")[3] // split("-")[2] | split(".")[0]) >= "20230328")
    | .package | split(".")[0]
')

mkdir -p ./os && cd ./os
for PACKAGE in ${PACKAGES}; do
    if [ ! -f ./${PACKAGE}.zip ]; then
        echo "--> ${PACKAGE} downloading"
        wget -nc ${REPO_BASE}/os/${PACKAGE}.zip
    else
        echo "--> ${PACKAGE} already present"
    fi
done
cd ../

echo ""
echo "Fetching 12.3 firmware"

# See the installer source for a list of URLs to firmware images
# https://github.com/AsahiLinux/asahi-installer/blob/main/src/main.py#L46-L89

mkdir -p ./ipsw && cd ./ipsw
wget -nc https://updates.cdn-apple.com/2022SpringFCS/fullrestores/071-08757/74A4F2A1-C747-43F9-A22A-C0AD5FB4ECB6/UniversalMac_12.3_21E230_Restore.ipsw
cd ../

echo "Updating install script"
perl -pi -e 's#REPO_BASE=https.*#REPO_BASE=/opt/asahi-fedora\nexport IPSW_BASE="\$REPO_BASE/ipsw"#' ./install
chmod +x ./install
